version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: honeyjar-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_VECTOR_BUCKET=${S3_VECTOR_BUCKET:-honeyjar-media-vectors}
      - NEWS_API_KEY=${NEWS_API_KEY}
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
      - honeyjar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: honeyjar-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    restart: unless-stopped
    networks:
      - honeyjar-network
    depends_on:
      - api

networks:
  honeyjar-network:
    driver: bridge

